services:
  api:
    build: ./api
    container_name: tanews_app_api
    hostname: web-api
    volumes: ["./api:/apicode"]
    ports:
      - 4000:4000
    env_file: ./api/.env

  db:
    env_file:
      - ./api/.env
    image: mysql:8.0
    container_name: tanews_app_db
    hostname: db
    volumes:
      - ./database-files:/docker-entrypoint-initdb.d/:ro
    ports:
      - 3200:3306

  # frontend:
  #   build: ./frontend
  #   container_name: tanews_app_frontend
  #   hostname: web-frontend
  #   ports:
  #     - 3000:8080
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules # Prevents issues with node_modules inside container
  #   environment:
  #     - NODE_ENV=development
  #     - CHOKIDAR_USEPOLLING=true # Fixes hot reload issues in Docker
  #   command: ["npm", "run", "dev"]
  #   depends_on:
  #     - api
